---

- hosts: all
  become: true
  tasks:

  - name: Update repo index
    apt:
      update_cache: yes

  - name: Install Apache 2.0 package and php
    apt:
      name: 
            - apache2
            - libapache2-mod-php
      state: latest
      update_cache: yes
    when : ansible_distribution == "Ubuntu"
