---

- hosts: all
  become: true
  tasks:

  - name: Update repo index
    apt:
      update_cache: yes

  - name: Install Apache 2.0 package
    apt:
      name: apache2
      state: latest

  - name: Add PHPH suupport for Apache
    apt:
      name: libapache2-mod-php
      state: latest
