---

- hosts: all
  become: true
  tasks:
  pre_tasks:

  - name: install updates Ubuntu
    tags: always
    apt:
            upgrade: dist
            update_cache: yes
    when : ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:

  - name: Update repo index
    tags: apache, apache2, ubuntu
    apt:
      name: 
            - apache2
            - libapache2-mod-php
      state: latest
    when : ansible_distribution == "Ubuntu"

  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy:
            src: default_site.html
            dest: /var/www/html/index.html
            owner: root
            group: root
            mode: 0644

- hosts: db_servers
  become: true
  tasks:
 
  - name : "Install Maria DB"
    tags: ubuntu, db, mariadb
    apt:
            name: mariadb-server
            state: latest
    when: ansible_distribution == "Ubuntu"


- hosts: file_servers
  become: true
  tasks:

  - name : install Samba package
    tags: samba
    package:
            name: samba
            state: latest
